# Cocotb Makefile for AIPP Silicon Proof

SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/aipp_parser.v
TOPLEVEL = aipp_parser
MODULE = test_aipp_parser

include $(shell cocotb-config --makefiles)/Makefile.sim







